name: atoll_attack
description: RTS game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.29.0 
  ordered_set: ^8.0.0
  collection: ^1.19.1
  fast_noise: ^2.0.0
  flutter_hooks: ^0.21.2
  flame_forge2d: ^0.19.0+2
  a_star: ^3.0.1
  riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  # Core Firebase services (only what we use)
  firebase_core: ^3.14.0
  firebase_database: ^11.3.7  # RTDB for multiplayer fallback
  
  # Multiplayer & Communication
  flutter_webrtc: ^0.14.1     # WebRTC for P2P multiplayer
  
  # Utilities
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  app_links: ^6.4.0           # Deep linking
  share_plus: ^11.0.0         # Share room codes
  logger: ^2.5.0              # Logging
  uuid: ^4.5.1                # Unique IDs
  rxdart: ^0.27.7             # Reactive streams
  
  # UI & Icons
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/turtle_ship.png
    - assets/maps/

  shaders:
    - shaders/island_water.frag