// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key',
    appId: 'your-web-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'atoll-attack',
    authDomain: 'atoll-attack.firebaseapp.com',
    databaseURL: 'https://atoll-attack-default-rtdb.firebaseio.com',
    storageBucket: 'atoll-attack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJrPFhYiVe1T1FcuCIUh5CA56nDlfq1M',
    appId: '1:563315369126:android:f3471e1bc6c0c7acb04067',
    messagingSenderId: '563315369126',
    projectId: 'atoll-attack',
    databaseURL: 'https://atoll-attack-default-rtdb.firebaseio.com',
    storageBucket: 'atoll-attack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAhz7WRoh4aKItEZMJLWYKfHZ9QFfGwBo',
    appId: '1:563315369126:ios:501d781392bb9177b04067',
    messagingSenderId: '563315369126',
    projectId: 'atoll-attack',
    databaseURL: 'https://atoll-attack-default-rtdb.firebaseio.com',
    storageBucket: 'atoll-attack.firebasestorage.app',
    iosBundleId: 'com.risney.games.atolls.atollWars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'atoll-attack', 
    databaseURL: 'https://atoll-attack-default-rtdb.firebaseio.com',
    storageBucket: 'atoll-attack.appspot.com',
    iosBundleId: 'com.risney.games.atoll',
  );
}